config/routes.rb
Rails.application.routes.draw do
    root "homes#index"
    get "/home/about", to: "homes#show", as: "homes_show"
    devise_for :users
    resources :users, only: [:index, :show, :edit, :update]
    resources :books, only: [:create, :index, :show, :edit, :update, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: {minimum: 2, maximum: 20 }
  validates :introduction, length: {maximum: 49 }
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  attachment :image 
  attachment :profile_image
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   root_path(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end  
  # def after_sign_up_path_for(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  
  # GET /resource/sign_in
  # def new
  # end

  # POST /resource/sign_in
  # def create  
  # end

  # DELETE /resource
  # def destroy
    
  # end
  
  # def after_sign_in_path_for(resource)
  # end 

  #ログアウト後のリダイレクト先
  # def after_sign_out_path_for(resource)
  # end 


  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user! #ユーザーを認証する

    def index
        @book = Book.new       
        @users = User.all
    end
    def show
        @book = Book.new       
        @user = User.find(params[:id])
        @books = @user.books
    end

    def edit 
        @user = User.find(params[:id])
        if current_user.id != @user.id
            redirect_to user_path(current_user)
        end
    end

    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            flash[:notice] = "You have updated user successfully."
            redirect_to user_path(@user.id)
        else
            render 'edit'
        end
    end

private 
    def user_params
        params.require(:user).permit(:name, :introduction, :profile_image)
    end
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="csrf-param" content="authenticity_token" />
    <meta name="csrf-token" content="BMwTJBNdiRr9x0t9TnyadI5GuxmVnoTjhBtdrMDF+dN3kJXf/k+mK9wjJrByvTWJCYLbvL6SAuCFwKDS0wuIdQ==" />
    <link rel="stylesheet" media="all" href="/assets/application-945628f9f95377705c9108ec9a9704e6f6ffa0767c02e34400d75b5be64fc1b7.css" data-turbolinks-track="reload" />
    <script src="/assets/application-11e027fe501efa6924bd87aa8f6ef7436fd1539022b412029c4a223dec9664f8.js" data-turbolinks-track="reload"></script>
  </head>

  <body>
    <div class="body">
      <div class="container">
      <%= form_for(@user) do |f| %>      
        <% if @user.errors.any? %>
          <div id="error_explanation" class="alert alert-danger">
            <h2><%= @user.errors.count %>errors prohibited this obj from being saved:</h2>
            <ul>
              <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
      <% end %>
      <h2>User info</h2>
      <%= form_for(@user) do |f| %>      
          <div class="field">
            <label for="username">name</label>
            <%# <%= f.label :name, "Name" でも良い %> 
            <%= f.text_field :name,class:"name"%>
          </div>
          <div class="field">
            <label for="user_image">image</label>
            <%# <%= f.label :profile_image_id, "Image" でも良い %> 
            <%= f.attachment_field :profile_image,class: "user_image" %>
          </div>
          <div class="field">
            <label for="user_introduction">introduction</label>
            <%# <%= f.label :introduction, "introduction" でも良い %> 
            <%= f.text_area :introduction,class:"introduction" %>
          </div>
          <div class="actions">
            <%= f.submit %>
          </div>
      <% end %>

    <footer>
        <div class="container">
  	        <div class="row">
    	        <div class="col-xs-3 col-xs-offset-9">
    		        <p>CopyRight Infratop.inc</p>
    	        </div>
            </div>
        </div>
    </footer>
  </body>
</html>

app/views/users/index.html.erb
<!DOCTYPE html>
<html>
  <body>
    <div class="body">
      <div class="container">
        <%= flash[:success] %>
      	<div class="row">
          <div class="col-xs-3">
            <h2>User info</h2>
            <%= attachment_image_tag current_user, :profile_image,size: "100x100",fallback: "no_image.jpg",class:"attachment user profile_image" %></td>
            <table class="table">
              <tbody>
                <tr></tr>
                <tr>
                  <th>name</th>
                  <th><%= current_user.name %></th>
                </tr>
                <tr>
                  <th>introduction</th>
                  <th><%= current_user.introduction %></th>
                </tr>
              </tbody>
            </table>

            <div class="row">
              <%= link_to "",edit_user_path(current_user.id),class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
            </div>

            <h2>New book</h2>
            <%= form_for(@book) do |f| %>

              <div class="field row">
                <label for="book_title">Title</label>
                <%= f.text_field :title,class:"col-xs-12 book_title" %>
              </div>

              <div class="field row">
                <label for="book_opinion">Opinion</label>
                <%= f.text_area :body,class:"col-xs-12 book_body" %>
              </div>

              <div class="actions row">
                <%= f.submit 'Create Book',class:"btn btn-primary col-xs-12" %>
              </div>

            <% end %>
          </div>

          <div class="col-xs-9">
            <h2>Users</h2>
            <table class="table">
              <thead>
                <tr>
                  <th>image</th>
                  <th>name</th>
                  <th colspan="3"></th>
                </tr>
              </thead>
              <% @users.each do |users| %>
                <tbody>
                  <tr>
                    <td><%= attachment_image_tag users, :profile_image,size: "40x40",fallback: "no_image.jpg",class:"attachment user profile_image fallback" %></td>
                    <td><%= users.name %></td>
                    <td><%= link_to "Show",user_path(users) %></td>
                  </tr>
                </tbody>
              <% end %>
            </table>
          </div>
        </div>
      </div>
    </div>

    <footer>
        <div class="container">
  	        <div class="row">
    	        <div class="col-xs-3 col-xs-offset-9">
    		        <p>CopyRight Infratop.inc</p>
    	        </div>
            </div>
        </div>
    </footer>

  </body>
</html>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
  <body>
    <div class="body">
      <div class="container">
        <p id="notice"><%= flash[:notice] %></p>
      	<div class="row">
          <div class="col-xs-3">
            <h2>User info</h2>
            <%= attachment_image_tag current_user, :profile_image,size: "100x100",class:"attachment user profile_image",fallback: "no_image.jpg" %></td>
            <table class="table">
              <tbody>
                <tr></tr>
                <tr>
                  <th>name</th>
                  <th><%= current_user.name %></th>
                </tr>
                <tr>
                  <th>introduction</th>
                  <th><%= current_user.introduction %></th>
                </tr>
              </tbody>
            </table>
            <div class="row">
              <% if  @user.id == current_user.id %>
                <%= link_to "",edit_user_path,class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user" %>
              <% else %>
                <%= link_to "",user_path(current_user.id),class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
              <% end %>
            </div>
            <h2>New book</h2>
            <%= form_for(@book) do |f| %>
              <div class="field row">
                <label for="book_title">Title</label>
                <%= f.text_field :title,class:"col-xs-12 book_title" %>
              </div>
              <div class="field row">
                <label for="book_opinion">Opinion</label>
                <%= f.text_area :body,class:"col-xs-12 book_body" %><br />
              </div>
              <div class="actions row">
                <%= f.submit "Create Book",class:"btn btn-primary col-xs-12" %>
              </div>
            <% end %>
          </div>  
          <div class="col-xs-9">
            <h2>Books</h2>
            <table class="table table-hover table-inverse">
              <thead>
                <tr>
                  <th></th>
                  <th>Title</th>
                  <th>Opinion</th>
                  <th colspan="3"></th>
                </tr>
              </thead>
              <tbody class="table table-hover table-inverse">
                <% @books.each do |book| %>
                  <tr>
                    <td><%= attachment_image_tag book.user,:profile_image,format: 'jpeg',size: "40x40",fallback: "no_image.jpg" %></td>
                    <td><%= link_to book.title, book_path(book.id) %></td>
                    <td><%= book.body %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  

    <footer>
        <div class="container">
  	        <div class="row">
    	        <div class="col-xs-3 col-xs-offset-9">
    		        <p>CopyRight Infratop.inc</p>
    	        </div>
            </div>
        </div>
    </footer>
  </body>
</html>