config/routes.rb
Rails.application.routes.draw do
    root "homes#index"
    get "/home/about", to: "homes#show", as: "homes_show"
    devise_for :users
    resources :users, only: [:index, :show, :edit, :update]
    resources :books, only: [:create, :index, :show, :edit, :update, :destroy]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <% if user_signed_in? %>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <nav class='nav navbar-nav navbar-left' >
          <span>Bookers</span>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", user_path(current_user.id), class: "glyphicon glyphicon-home " %></li>
            <li><%= link_to "Users", users_path, class: "glyphicon glyphicon-user" %></li>
            <li><%= link_to "Books", books_path, class: "glyphicon glyphicon-book" %></li>
            <li><%= link_to "logout", destroy_user_session_path, :notice => "locked", class: "glyphicon glyphicon-log-out", method: :delete %></li>
          </ul>
        </nav>  
      </div>
    </header>
  <% else %>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <nav class='nav navbar-nav navbar-left' >
          <span>Bookers</span>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", root_path, class: "glyphicon glyphicon-home home" %></li>
            <li><%= link_to "About", homes_show_path, class: "glyphicon glyphicon-link about" %></li>
            <li><%= link_to "Sign up", new_user_registration_path, class: "glyphicon glyphicon-edit sign_up" %></li>
            <li><%= link_to "login", new_user_session_path, class: "glyphicon glyphicon-log-in sign_in" %></li>
          </ul>
        </nav>
      </div>
    </header>
  <% end %><br>
  
  <%= yield %>
</html>